<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Input Mapping</name>
  <uuid>09d44083-d1e9-44cf-8193-f14b5b06aa87</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the age is the age of Customer , 
		the bmi is the bmi of Customer , 
		the bp is the bp of Customer , 
		the gender is the gender of Customer ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
