<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Output</name>
  <uuid>51cbcad8-02b1-4a76-900f-367db378aa30</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the prediction of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
