<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Invalid Customers</name>
  <uuid>3f716bd2-e8f7-4d4c-96a4-df610544809a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Unable" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
