<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Valid Customer Prediction</name>
  <uuid>dd473e26-ff2f-4c57-9438-804ac200405e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Valid 
then
	  set decision to the drug selector computed from
      Customer being customer ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
