<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Valid</name>
  <uuid>832144de-256d-47f6-be2b-891788b284ea</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if all of the following conditions are true : 
	- the age of customer is at least 16 and less than 80
	- the bmi of customer is at least 5 and less than 45
	- the bp of customer is one of { "L", "M", "H"}
	- the gender of customer is one of { "M", "F"}
then
	set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
